# Generated by Django 3.2.7 on 2021-12-02 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.member'),
        ),
    ]
