# Generated by Django 3.2.7 on 2021-12-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_alter_gift_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='link',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
